pipeline {
    agent any

    environment {
        EC2_USER     = "ubuntu"
        EC2_HOST     = "${env.EC2_HOST ?: 'localhost'}"
        SSH_CRED_ID  = "ec2-ssh-key"
    }

    stages {
        stage('Deploy to EC2') {
            steps {
                echo 'Reading ECR metadata details generated by AWS CodeBuild...'
                
                script {
                    def imageDetail = readJSON file: 'imageDetail.json'
                    env.ECR_IMAGE_URI = imageDetail.ImageURI
                    echo "Deploying container version: ${env.ECR_IMAGE_URI}"
                }

                sshagent([SSH_CRED_ID]) {
                    sh "ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} 'mkdir -p ~/app'"
                    sh "scp -o StrictHostKeyChecking=no docker-compose.yml nginx.conf ${EC2_USER}@${EC2_HOST}:~/app/"
                    sh """
                        ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} '
                            cd ~/app
                            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${env.ECR_IMAGE_URI.split('/')[0]}
                            docker pull ${env.ECR_IMAGE_URI}
                            export ECR_IMAGE_URI=${env.ECR_IMAGE_URI}
                            docker compose down --remove-orphans || true
                            docker compose up -d
                        '
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment complete! Inventory backend is live on port 80.'
        }
        failure {
            echo 'Deployment failed. Check build logs.'
        }
    }
}
